### ISSUE TITLE
will this work on rails 4?

### ISSUE THREAD

**Issue by netpenthe** [ezcater/activerecord-postgres_pub_sub#16]

**Comment by tjwp** [comment]
Hi @netpenthe - in its current form the gem will not work with Rails 4 because we restrict the ActiveRecord version: https://github.com/ezcater/activerecord-postgres_pub_sub/blob/master/activerecord-postgres_pub_sub.gemspec#L43

I created this [branch](https://github.com/ezcater/activerecord-postgres_pub_sub/tree/tjwp-ar-4) to test against Rails 4 and the tests pass.

If you'd like to try this with your application you can specify the branch `tjwp-ar-4` in your Gemfile.

**Comment by netpenthe** [comment]
thanks - i'll give it a go.
